### ISSUE TITLE
Estudar criacao de lib atraves do NestJS

### ISSUE THREAD

**Issue by yuripinheirot** [zrp/keycloak-nest-core#5]
O proprio NestJS da suporte para criacao de libs: [creating-libraries](https://docs.nestjs.com/cli/libraries#creating-libraries)

Estudar como funciona a criacao de libs, e trazer para o projeto ideias e solucoes

**Comment by LuizJuniorZrp** [comment]
1. Estrutura do Projeto
Ao trabalhar com bibliotecas no NestJS, normalmente você usa o Nest CLI para criar uma library dentro de um workspace monorepo.

`nest generate library my-library`

2. Configurar o package.json da Biblioteca
Dentro da pasta libs/my-library, você encontrará um arquivo package.json. Configure as informações relevantes, como nome, versão e dependências.

Exemplo de package.json:

`{
  "name": "@meu-namespace/my-library",
  "version": "1.0.0",
  "description": "Minha biblioteca NestJS",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "files": [
    "dist"
  ],
  "scripts": {
    "build": "tsc -p tsconfig.build.json"
  },
  "peerDependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0"
  }
}
`

3. Compilar a Biblioteca
Certifique-se de compilar a biblioteca para JavaScript (se estiver usando TypeScript). Crie um arquivo tsconfig.build.json na raiz da pasta da sua biblioteca para garantir que a biblioteca será corretamente compilada.

Exemplo de tsconfig.build.json:

`{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "outDir": "./dist",
    "rootDir": "./src"
  },
  "exclude": ["**/*.spec.ts", "**/*.test.ts"]
}`

`npm run build`

`npm login`

`npm publish --access public`

`npm install @meu-namespace/my-library`

**Comment by yuripinheirot** [comment]
O que foi feito: 

1. Foi criado uma nova estrutura de desenvolvimento de biblioteca dentro do projeto
2. Foi adaptado o projeto para que ao buildar, ele inclua essa nova estrutura de lib
3. Ao iniciar o projeto, deve-se rodar dois comandos separadamente:
   - docker compose up app
   - yarn build:lib:watch (esse comando serve para que ao fazermos alguma alteração na lib, surtir efeito no projeto final)
